# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recobj',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recobj',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userobj',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
