# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobss', '0002_auto_20180224_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='recobj',
            name='applns',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userobj',
            name='appln',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userobj',
            name='skill1',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userobj',
            name='skill2',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userobj',
            name='skill3',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
