# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobss', '0003_auto_20180225_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='userobj',
            name='message',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
